### ISSUE TITLE
Brownie Account Support

### ISSUE THREAD

**Issue by ShadeUndertree** [ApeWorX/eip712#4]
### Elevator pitch:

Integrate eip712 into [brownie's](https://github.com/eth-brownie/brownie) local account class so that Brownie accounts can sign eip712 messages.

### Value:

The first place we're going to use this in yearn-vaults, to get rid of the dependency on eth-account in the test suite. Example:

https://github.com/yearn/yearn-vaults/blob/67cf46f3/tests/conftest.py#L91-L139

Other than that, this will be a useful feature for end users of Brownie.

### Dependencies:

None.

### Design approach:

Design is all set. See the task list.

### Task list:

* [x] Copy whatever code is needed from eth_account to implement the account signing logic
* [x] Use the eip712 package in brownie to implement `sign_message` on e.g. the `_PrivateKeyAccount` class
* [x] Write new tests for eip712 and brownie using the new code 
* [x] Submit PR to brownie for adding the eip712 dependency and using eip712 to implement `sign_message`

### Estimated completion date:
2021-05-26.

### Design review:

Do not signoff unless: 1) agreed the tasks and design approach will achieve acceptance and 2) the work can be completed by one person within the SLA. Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
LGTM

**Comment by lost-theory** [comment]
This was finished on Jul 1st.
